### ISSUE TITLE
save-my-tabs has stopped working.

### ISSUE THREAD

**Issue by tony4newton** [salvoventura/save-my-tabs#7] opened 2020-08-14 23:10 UTC
I went to options and unticked Enable/Disable to pause it for a while but when I went back and ticked the box, it hasn't saved anything since.

**Comment by salvoventura** [comment] 2020-08-15 00:03
Hello @tony4newton ,
 thanks for using "Save my tabs!" and for reporting this issue.

 I have few additional questions to start: you are referring to the Autosave, of course.
 1. What's your combination of OS/Browser?
 2. Did you press the "Save" button in the options dialog after ticking the box?
 3. When you reopen the dialog after saving, is the enable/disable box checked/unchecked?

 Thank you for your help.

 Best,
 Salvo

**Comment by tony4newton** [comment] 2020-08-15 08:49
Hi Salvo,



Thank you for your quick response.



1. Windows 10/Firefox.

2. Yes, I did press the "Save" button in the options dialogue after ticking the box.

3. The enable/disable box is checked.



I have done this before without any problems.

I have tried removing save-my-tabs, shutting down and restarting my computer, then adding save-my-tabs.



Regards,

Tony


On 15 August 2020 at 1:04, salvoventura <notifications@github.com> wrote:






Hello @tony4newton ,
thanks for using "Save my tabs!" and for reporting this issue.

I have few additional questions to start: you are referring to the Autosave, of course.

What's your combination of OS/Browser?
Did you press the "Save" button in the options dialog after ticking the box?
When you reopen the dialog after saving, is the enable/disable box checked/unchecked?

Thank you for your help.

Best,
Salvo

**Comment by salvoventura** [comment] 2020-08-17 02:56
Hi Tony,
 I am trying to reproduce, however it is currently working fine on my own PC (Win10+FF). 

 Allow me some more time to gather a better set of questions to ask you, which might help better understand what's going on. 

 Thanks for your help,
 Salvo

**Comment by salvoventura** [comment] 2020-09-06 06:43
Hey Tony,
 sorry for the long delay. I have been running Save-my-tabs with auto-save on for some time now; I have tried to stop/start it multiple times, but I cannot trigger the misbehavior. From the code, the only thing I can think of is something (odd) preventing the timers to fire. Which would be really odd. Did you recently add an extension before this new behavior started happening?

Cheers,
Salvo

**Comment by tony4newton** [comment] 2020-09-06 23:00
Hi Salvo,


No worries at all, thanks for taking the time to look into it.


You will be pleased to know that I just reinstalled Save-my-tabs there now, and it's working fine.
It could have been Privacy Possum blocking Save-my-tabs, as I had another issue were my, iCloud email wouldn't open, and I had recently added it as it was a highly rated app. anyway I uninstalled it, and iCloud email started working again. I think Privacy Possum it's a bit overzealous. Could it have been that?


Cheers Salvo I'm glad to have it back,
Tony

On 6 September 2020 at 7:44, salvoventura <notifications@github.com> wrote:






Hey Tony,
sorry for the long delay. I have been running Save-my-tabs with auto-save on for some time now; I have tried to stop/start it multiple times, but I cannot trigger the misbehavior. From the code, the only thing I can think of is something (odd) preventing the timers to fire. Which would be really odd. Did you recently add an extension before this new behavior started happening?

Cheers,
Salvo

**Comment by salvoventura** [comment] 2020-09-06 23:59
Thanks Tony, that's valuable information at least for further information. It might be, because I see PP does some "monkey-patching" of methods, and that *might* include what saves the state in my add-on. Glad that it's working for you again.

**Comment by salvoventura** [comment] 2020-12-31 20:49
Closing this issue as I believe there's nothing I can do to prevent other add-ons from hijacking methods

**Closed by salvoventura** 2020-12-31 20:49 UTC
